#TAMAÑOS APLICADA PARA LA SCREEN Y EL TAMAÑO DE LO QUE SE DIBUJA EN PANTALLA

WIDTH, HEIGHT = 1280, 720
ENTITY = 64
GRASS = 64
TREE = 64
SMALL_STONE = 16
MINERAL_IRON = 32


#MOVIMIENTO DE ENTIDADES VIVAS
BASE_SPEED = 1
PLAYER_BASE_SPEED = 5
ENEMY_BASE_SPEED = 1.5 



#DICCIONARIO DE LAS DIRECCIONES ESTATICAS
IDLE_FRAMES ={
    "down": 0,
    "up": 0,
    "right": 0,
    "left": 1
}

#ANIMACIONES
FRAME_SIZE = 32
ACTION_FRAME_SIZE = 48
ANIMATION_DELAY = 100
RUNNING_ANIMATION_DELAY = 50
ATTACK_ANIMATION_DELAY = 200


BASIC_FRAMES = 6
IDLE_DOWN = 0
IDLE_RIGHT = 1
IDLE_UP = 2
WALK_DOWN = 3
WALK_RIGHT = 4
WALK_UP = 5



#colores

WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
BROWN = (169, 69, 19)
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)


#BARRAS DE ESTADO
MAX_ENERGY = 100
MAX_FOOD = 100
MAX_THIRST = 100
MAX_STAMINA = 100

#COLORES PARA LAS BARRAS DE ESTADO 
ENERGY_COLOR = (255, 255, 0)
FOOD_COLOR =(255, 165, 0)
THIRST_COLOR =(0, 191, 255)
STAMINA_COLOR = (124, 252, 0)
BAR_BACKGROUND =(100, 100, 100)

#PROPIEDADES PARA LA CLASE ENTITIES
MAX_HEALTH = 100
BASE_FORCE = 10
BASE_WEAPON_SKILL = 1
BASE_ARMOR = 1
BASE_CRITICAL_DAMAGE = 1
BASE_MAGIC_RESISTENCE = 1

#INTERVALO PARA EL TIEMPO
STATUS_UPDATE_TIMER = 1000

#SISTEMA DE DIA Y DE NOCHE
DAY_LENGTH = 24000
DAWN_TIME = 6000
MORNING_TIME = 8000
DUSK_TIME = 18000
MIDNIGHT = 24000
MAX_DARKNESS = 200

#COLORES PARA ILUMINACION
NINGHT_COLOR = (20, 20, 50)
DAY_COLOR = (255, 255, 255)
DAWN_DUSK_COLOR = (255, 193, 137)

#CONSTANTES PARA VELOCUDAD DE DISMINUCION DE ESTADOS
FOOD_DECREASE_RATE = 0.01
THIRST_DECREASE_RATE = 0.02
ENERGY_DECREASE_RATE = 0.005
ENERGY_INCREASE_RATE = 0.001
MOVEMENT_ENERGY_COST = 0.001

#CONSTANTES PARA CPRRER
WALK_SPEED = 5
RUN_SPEED = 10
STAMINA_DECREASE_RATE = 0.05
STAMINA_INCREASE_RATE = 0.02
RUN_FOOD_DECREASE_MULTIPLER = 2
RUN_THIRST_DECREASE_MULTIPLER = 2


#CONSTANTES PARA INVENTARIO
SLOT_SIZE = 64
HOTBAR_SLOTS = 8
INVENTORY_COLS = 4
INVENTORY_ROWS = 5
MARGIN = 10

#COMO ESTO NO VA A CAMBIAR AQUI VOY A PONER LA POSICION DE LA HOTBAR
HOTBAR_X = (WIDTH - (SLOT_SIZE * HOTBAR_SLOTS )) // 2
HOTBAR_Y = HEIGHT - SLOT_SIZE - MARGIN

# PARA LA POSICION DEL INVENTARIO EL QUE SE ABRE CON LA TECLA I
INVENTORY_X = (WIDTH - (SLOT_SIZE * INVENTORY_COLS)) // 2
INVENTORY_Y = (HEIGHT - (SLOT_SIZE * INVENTORY_ROWS)) // 2

#constantes para el crafteo 
CRAFTING_GRID_SIZE = 2
CRAFTING_RESULT_SLOT_X = INVENTORY_X + (SLOT_SIZE * (INVENTORY_COLS + 1))
CRAFTING_RESULT_SLOT_Y = INVENTORY_Y 
CRAFTING_GRID_X = INVENTORY_X + (SLOT_SIZE * (INVENTORY_COLS + 1))
CRAFTING_GRID_Y = INVENTORY_Y + SLOT_SIZE * 2

#HANDS SLOSTS CONSTANTS
LEFT_HAND_SLOT_X = HOTBAR_X - SLOT_SIZE - MARGIN
LEFT_HAND_SLOT_Y = HOTBAR_Y 
RIGHT_HAND_SLOT_X = HOTBAR_X + (SLOT_SIZE * HOTBAR_SLOTS) + MARGIN
RIGHT_HAND_SLOT_Y = HOTBAR_Y

#CONSTANTES PARA EL USO DE ANIMACIONES EN LOS ATAQUES Y HERRAMIENTAS
AXE_COLS =2
AXE_FRAMES = 2
AXE_ANIMATION_DELAY = 200


#Colores del inventario para que se vea chido
SLOT_COLOR = (139, 139, 139)
SLOT_BORDER = (100, 100, 100)
SLOT_HOVER = (160, 160, 160)


#PROPIEDADES PARA LA BATALLA
MELEE_ATTACK_DISTANCE = 50
RANGED_ATTACK_DISTANCE = 200
DAMAGE_WITH_GUN = 25
DAMAGE_MELEE = 5
# Sistema de balas
BASE_BULLET_SPEED = 8
BULLET_LIFETIME = 3000 
CHUNK_SIZE = 1000  
#PROPIEDADES BASE DE LAS ARMAS (LUEGO LO AMPLIO)
BASE_BULLET_SPEED = 10



#CONSTATES PARA EL AGUA
WATER_COLOR = (64, 164, 223, 180)
WATER_MOVEMENT_MULTIPLIER = 0.5
WATER_GENERATION_PROBABILITY = 0.3
WATER_THIRST_RECOVER = 5

#CONSTANTES PARA LA GENERACION DE RECURSOS
MINERAL_IRON_PROBABILITY = 0.015




